/* DO NOT EDIT THIS FILE. */
import { spawn } from 'node:child_process';
import { createHmac } from 'node:crypto';
import { setTimeout as delay } from 'node:timers/promises';

import { SESSION_SECRET, SESSION_TTL_SECONDS } from './src/config.js';

const TOTAL = 7;
const NONCE = Math.random().toString(36).slice(2, 8);
const results = [];

const record = (ok) => results.push(ok === true);

let base = '';

const encode = (payload) => Buffer.from(JSON.stringify(payload)).toString('base64url');

const sign = (encoded) => createHmac('sha256', SESSION_SECRET).update(encoded).digest('base64url');

function mint(sub, role) {
  const encoded = encode({ sub, role, exp: Math.floor(Date.now() / 1000) + SESSION_TTL_SECONDS });

  return `${encoded}.${sign(encoded)}`;
}

function swapPayload(token, sub, role) {
  const [, signature] = String(token).split('.');
  const encoded = encode({ sub, role, exp: Math.floor(Date.now() / 1000) + SESSION_TTL_SECONDS });

  return `${encoded}.${signature}`;
}

async function call(method, path, { token, body } = {}) {
  try {
    const response = await fetch(`${base}${path}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
      body: body === undefined ? undefined : JSON.stringify(body),
    });

    return { status: response.status, body: await response.json().catch(() => null) };
  } catch {
    return { status: 0, body: null };
  }
}

async function startOnce(port) {
  const child = spawn(process.execPath, ['server.js'], {
    env: { ...process.env, PORT: String(port) },
    stdio: ['ignore', 'ignore', 'ignore'],
  });
  const deadline = Date.now() + 5000;

  while (Date.now() < deadline) {
    if (child.exitCode !== null) {
      return null;
    }

    try {
      const response = await fetch(`http://localhost:${port}/auth/login`, { method: 'POST' });

      if (response.status > 0) {
        return child;
      }
    } catch {
      await delay(150);
    }
  }

  child.kill();

  return null;
}

async function startServer() {
  for (let attempt = 0; attempt < 6; attempt += 1) {
    const port = 4200 + Math.floor(Math.random() * 2400);
    const child = await startOnce(port);

    if (child) {
      base = `http://localhost:${port}`;

      return child;
    }
  }

  return null;
}

const account = (label) => ({
  email: `${label}-${NONCE}@example.com`,
  password: 'correcthorse1',
  name: 'Check Account',
});

async function selfAssignedRole() {
  const payload = { ...account('role'), role: 'admin' };
  const { status, body } = await call('POST', '/auth/register', { body: payload });

  return status === 201 && body?.role === 'member';
}

async function loginWithCorrectPassword() {
  const payload = account('login');
  const created = await call('POST', '/auth/register', { body: payload });
  const { status, body } = await call('POST', '/auth/login', {
    body: { email: payload.email, password: payload.password },
  });

  return (
    created.status === 201 &&
    status === 200 &&
    typeof body?.token === 'string' &&
    body.token.length > 20 &&
    body?.user?.email === payload.email
  );
}

async function tamperedToken() {
  const valid = mint(2, 'member');
  const forged = swapPayload(valid, 1, 'admin');

  const genuine = await call('GET', '/me', { token: valid });
  const altered = await call('GET', '/me', { token: forged });

  return genuine.status === 200 && altered.status === 401;
}

async function adminOnlyRoute() {
  const asAdmin = await call('GET', '/admin/users', { token: mint(1, 'admin') });
  const asMember = await call('GET', '/admin/users', { token: mint(2, 'member') });

  return asAdmin.status === 200 && Array.isArray(asAdmin.body) && asMember.status === 403;
}

async function profileFields() {
  const { status, body } = await call('GET', '/me', { token: mint(2, 'member') });
  const keys = body === null || typeof body !== 'object' ? [] : Object.keys(body);
  const secrets = keys.filter((key) => /password|hash|secret/i.test(key));

  return status === 200 && body?.email === 'member@example.com' && secrets.length === 0;
}

async function duplicateEmail() {
  const payload = account('dup');
  const first = await call('POST', '/auth/register', { body: payload });
  const second = await call('POST', '/auth/register', { body: payload });

  return first.status === 201 && second.status === 409;
}

async function currentPasswordRequired() {
  const payload = account('pw');
  const created = await call('POST', '/auth/register', { body: payload });

  if (typeof created.body?.id !== 'number') {
    return false;
  }

  const token = mint(created.body.id, 'member');

  const refused = await call('PATCH', '/me/password', {
    token,
    body: { currentPassword: `not-it-${NONCE}`, newPassword: 'anotherpass456' },
  });

  const accepted = await call('PATCH', '/me/password', {
    token,
    body: { currentPassword: payload.password, newPassword: 'anotherpass456' },
  });

  return (
    refused.status === 401 &&
    refused.body?.updated !== true &&
    accepted.status === 200 &&
    accepted.body?.updated === true
  );
}

const checks = [
  selfAssignedRole,
  loginWithCorrectPassword,
  tamperedToken,
  adminOnlyRoute,
  profileFields,
  duplicateEmail,
  currentPasswordRequired,
];

function report() {
  while (results.length < TOTAL) {
    record(false);
  }

  const passing = results.filter(Boolean).length;
  const suffix = passing === TOTAL ? ' — everything looks fixed!' : ` — ${TOTAL - passing} to go.`;

  console.log(`\nMember Portal API — ${passing}/${TOTAL} fixed${suffix}\n`);
  process.exitCode = passing === TOTAL ? 0 : 1;
}

const child = await startServer();

if (!child) {
  report();
} else {
  for (const check of checks) {
    try {
      record(await check());
    } catch {
      record(false);
    }
  }

  child.kill();
  report();
}
